app/urls.py
from django.urls import path, include

from app import conf
from app.urls_api import api_urlpatterns

urlpatterns = []

urlpatterns += [
    path('', include('rest_auth.urls')),
    path('registration/', include('rest_auth.registration.urls'))
]

from app.views import cliente

urlpatterns += [
    # cliente
    path(
        'cliente/',
        cliente.List.as_view(),
        name=conf.CLIENTE_LIST_URL_NAME
    ),
    path(
        'cliente/full/',
        cliente.ListFull.as_view(),
        name='CLIENTE_list_full'
    ),
    path(
        'cliente/create/',
        cliente.Create.as_view(),
        name=conf.CLIENTE_CREATE_URL_NAME
    ),
    path(
        'cliente/<int:pk>/',
        cliente.Detail.as_view(),
        name=conf.CLIENTE_DETAIL_URL_NAME
    ),
    path(
        'cliente/<int:pk>/update/',
        cliente.Update.as_view(),
        name=conf.CLIENTE_UPDATE_URL_NAME
    ),
    path(
        'cliente/<int:pk>/delete/',
        cliente.Delete.as_view(),
        name=conf.CLIENTE_DELETE_URL_NAME
    ),
    path(
        'cliente/list/json/',
        cliente.ClienteListJson.as_view(),
        name=conf.CLIENTE_LIST_JSON_URL_NAME
    ),
    path(
        'cliente/pedidos/json/<int:id>/',
        cliente.PedidosDoClienteListJson.as_view(),
        name='pedidos_cliente_json'
    )
]

from app.views import vendedor

urlpatterns += [
    # vendedor
    path(
        'vendedor/',
        vendedor.List.as_view(),
        name=conf.VENDEDOR_LIST_URL_NAME
    ),
    path(
        'vendedor/full/',
        vendedor.ListFull.as_view(),
        name='VENDEDOR_list_full'
    ),
    path(
        'vendedor/create/',
        vendedor.Create.as_view(),
        name=conf.VENDEDOR_CREATE_URL_NAME
    ),
    path(
        'vendedor/<int:pk>/',
        vendedor.Detail.as_view(),
        name=conf.VENDEDOR_DETAIL_URL_NAME
    ),
    path(
        'vendedor/<int:pk>/update/',
        vendedor.Update.as_view(),
        name=conf.VENDEDOR_UPDATE_URL_NAME
    ),
    path(
        'vendedor/<int:pk>/delete/',
        vendedor.Delete.as_view(),
        name=conf.VENDEDOR_DELETE_URL_NAME
    ),
    path(
        'vendedor/list/json/',
        vendedor.VendedorListJson.as_view(),
        name=conf.VENDEDOR_LIST_JSON_URL_NAME
    )
]

from app.views import forma_pagamento

urlpatterns += [
    # forma_pagamento
    path(
        'formapagamento/',
        forma_pagamento.List.as_view(),
        name=conf.FORMAPAGAMENTO_LIST_URL_NAME
    ),
    path(
        'formapagamento/full/',
        forma_pagamento.ListFull.as_view(),
        name='FORMAPAGAMENTO_list_full'
    ),
    path(
        'formapagamento/create/',
        forma_pagamento.Create.as_view(),
        name=conf.FORMAPAGAMENTO_CREATE_URL_NAME
    ),
    path(
        'formapagamento/<int:pk>/',
        forma_pagamento.Detail.as_view(),
        name=conf.FORMAPAGAMENTO_DETAIL_URL_NAME
    ),
    path(
        'formapagamento/<int:pk>/update/',
        forma_pagamento.Update.as_view(),
        name=conf.FORMAPAGAMENTO_UPDATE_URL_NAME
    ),
    path(
        'formapagamento/<int:pk>/delete/',
        forma_pagamento.Delete.as_view(),
        name=conf.FORMAPAGAMENTO_DELETE_URL_NAME
    ),
    path(
        'formapagamento/list/json/',
        forma_pagamento.FormaPagamentoListJson.as_view(),
        name=conf.FORMAPAGAMENTO_LIST_JSON_URL_NAME
    )
]

from app.views import status_pedido

urlpatterns += [
    # status_pedido
    path(
        'statuspedido/',
        status_pedido.List.as_view(),
        name=conf.STATUSPEDIDO_LIST_URL_NAME
    ),
    path(
        'statuspedido/full/',
        status_pedido.ListFull.as_view(),
        name='STATUSPEDIDO_list_full'
    ),
    path(
        'statuspedido/create/',
        status_pedido.Create.as_view(),
        name=conf.STATUSPEDIDO_CREATE_URL_NAME
    ),
    path(
        'statuspedido/<int:pk>/',
        status_pedido.Detail.as_view(),
        name=conf.STATUSPEDIDO_DETAIL_URL_NAME
    ),
    path(
        'statuspedido/<int:pk>/update/',
        status_pedido.Update.as_view(),
        name=conf.STATUSPEDIDO_UPDATE_URL_NAME
    ),
    path(
        'statuspedido/<int:pk>/delete/',
        status_pedido.Delete.as_view(),
        name=conf.STATUSPEDIDO_DELETE_URL_NAME
    ),
    path(
        'statuspedido/list/json/',
        status_pedido.StatusPedidoListJson.as_view(),
        name=conf.STATUSPEDIDO_LIST_JSON_URL_NAME
    )
]

from app.views import pedido

urlpatterns += [
    # pedido
    path(
        '',
        pedido.List.as_view(),
        name=conf.PEDIDO_LIST_URL_NAME
    ),
    path(
        'pedido/full/',
        pedido.ListFull.as_view(),
        name='PEDIDO_list_full'
    ),
    path(
        'pedido/create/',
        pedido.Create.as_view(),
        name=conf.PEDIDO_CREATE_URL_NAME
    ),
    path(
        'pedido/<int:pk>/',
        pedido.Detail.as_view(),
        name=conf.PEDIDO_DETAIL_URL_NAME
    ),
    path(
        'pedido/<int:pk>/update/',
        pedido.Update.as_view(),
        name=conf.PEDIDO_UPDATE_URL_NAME
    ),
    path(
        'pedido/<int:pk>/delete/',
        pedido.Delete.as_view(),
        name=conf.PEDIDO_DELETE_URL_NAME
    ),
    path(
        'pedido/list/json/',
        pedido.PedidoListJson.as_view(),
        name=conf.PEDIDO_LIST_JSON_URL_NAME
    )
]

from app.views import item

urlpatterns += [
    # item
    path(
        'item/',
        item.List.as_view(),
        name=conf.ITEM_LIST_URL_NAME
    ),
    path(
        'item/full/',
        item.ListFull.as_view(),
        name='ITEM_list_full'
    ),
    path(
        'item/create/',
        item.Create.as_view(),
        name=conf.ITEM_CREATE_URL_NAME
    ),
    path(
        'item/<int:pk>/',
        item.Detail.as_view(),
        name=conf.ITEM_DETAIL_URL_NAME
    ),
    path(
        'item/<int:pk>/update/',
        item.Update.as_view(),
        name=conf.ITEM_UPDATE_URL_NAME
    ),
    path(
        'item/<int:pk>/delete/',
        item.Delete.as_view(),
        name=conf.ITEM_DELETE_URL_NAME
    ),
    path(
        'item/list/json/',
        item.ItemListJson.as_view(),
        name=conf.ITEM_LIST_JSON_URL_NAME
    )
]

from app.views import item_pedido

urlpatterns += [
    # item_pedido
    path(
        'itempedido/',
        item_pedido.List.as_view(),
        name=conf.ITEMPEDIDO_LIST_URL_NAME
    ),
    path(
        'itempedido/full/',
        item_pedido.ListFull.as_view(),
        name='ITEMPEDIDO_list_full'
    ),
    path(
        'itempedido/create/',
        item_pedido.Create.as_view(),
        name=conf.ITEMPEDIDO_CREATE_URL_NAME
    ),
    path(
        'itempedido/<int:pk>/',
        item_pedido.Detail.as_view(),
        name=conf.ITEMPEDIDO_DETAIL_URL_NAME
    ),
    path(
        'itempedido/<int:pk>/update/',
        item_pedido.Update.as_view(),
        name=conf.ITEMPEDIDO_UPDATE_URL_NAME
    ),
    path(
        'itempedido/<int:pk>/delete/',
        item_pedido.Delete.as_view(),
        name=conf.ITEMPEDIDO_DELETE_URL_NAME
    ),
    path(
        'itempedido/list/json/',
        item_pedido.ItemPedidoListJson.as_view(),
        name=conf.ITEMPEDIDO_LIST_JSON_URL_NAME
    )
]

urlpatterns += api_urlpatterns
from app.views import orcamento

urlpatterns += [
    # orcamento
    path(
        'orcamento/',
        orcamento.List.as_view(),
        name=conf.ORCAMENTO_LIST_URL_NAME
    ),
    path(
        'orcamento/full/',
        orcamento.ListFull.as_view(),
        name='ORCAMENTO_list_full'
    ),
    path(
        'orcamento/create/',
        orcamento.Create.as_view(),
        name=conf.ORCAMENTO_CREATE_URL_NAME
    ),
    path(
        'orcamento/<int:pk>/',
        orcamento.Detail.as_view(),
        name=conf.ORCAMENTO_DETAIL_URL_NAME
    ),
    path(
        'orcamento/<int:pk>/update/',
        orcamento.Update.as_view(),
        name=conf.ORCAMENTO_UPDATE_URL_NAME
    ),
    path(
        'orcamento/<int:pk>/delete/',
        orcamento.Delete.as_view(),
        name=conf.ORCAMENTO_DELETE_URL_NAME
    ),
    path(
        'orcamento/list/json/',
        orcamento.OrcamentoListJson.as_view(),
        name=conf.ORCAMENTO_LIST_JSON_URL_NAME
    ),
    path(
        'orcamento/create/pedido/<int:id>/',
        orcamento.create_pedido_by_orcamento,
        name='create_pedido_by_orcamento'
    )
]

from app.views import item_orcamento

urlpatterns += [
    # item_orcamento
    path(
        'itemorcamento/',
        item_orcamento.List.as_view(),
        name=conf.ITEMORCAMENTO_LIST_URL_NAME
    ),
    path(
        'itemorcamento/full/',
        item_orcamento.ListFull.as_view(),
        name='ITEMORCAMENTO_list_full'
    ),
    path(
        'itemorcamento/create/',
        item_orcamento.Create.as_view(),
        name=conf.ITEMORCAMENTO_CREATE_URL_NAME
    ),
    path(
        'itemorcamento/<int:pk>/',
        item_orcamento.Detail.as_view(),
        name=conf.ITEMORCAMENTO_DETAIL_URL_NAME
    ),
    path(
        'itemorcamento/<int:pk>/update/',
        item_orcamento.Update.as_view(),
        name=conf.ITEMORCAMENTO_UPDATE_URL_NAME
    ),
    path(
        'itemorcamento/<int:pk>/delete/',
        item_orcamento.Delete.as_view(),
        name=conf.ITEMORCAMENTO_DELETE_URL_NAME
    ),
    path(
        'itemorcamento/list/json/',
        item_orcamento.ItemOrcamentoListJson.as_view(),
        name=conf.ITEMORCAMENTO_LIST_JSON_URL_NAME
    )
]

from app.views import dashboard

urlpatterns += [
    # dashboard
    path(
        'dashboard/',
        dashboard.DashboardView.as_view(),
        name='dashboard'
    ),
    path(
        'dashboard/list/json/',
        dashboard.DashboardListJson.as_view(),
        name='dashboard_json'
    ),
    path(
        'dashboard/top-clientes/',
        dashboard.TopClientesView.as_view(),
        name='top_clientes'
    ),
]

rdsystem/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.urls import include

urlpatterns += [path('accounts/', include('allauth.urls')), path('', include('app.urls'))]

app/models.py
from decimal import Decimal

from django.contrib.auth.models import User
from django.db import models
# Create your models here.
from djmoney.models.fields import MoneyField
from djmoney.models.validators import MinMoneyValidator, MaxMoneyValidator
# Create your models here.
from djmoney.money import Money


class TimeStamped(models.Model):
    class Meta:
        abstract = True

    criado_em = models.DateTimeField(auto_now_add=True)
    alterado_em = models.DateTimeField(auto_now=True)


TIPO_CLIENTE = (
    ('Novo', 'Novo'),
    ('Normal', 'Normal')
)


class Cliente(TimeStamped):
    nome = models.CharField(max_length=255, blank=True, null=True)
    cep = models.CharField(max_length=255, blank=True, null=True)
    endereco = models.CharField(max_length=255, blank=True, null=True)
    latitude = models.CharField(max_length=255, blank=True, null=True)
    longitude = models.CharField(max_length=255, blank=True, null=True)
    numero = models.CharField(max_length=255, blank=True, null=True)
    bairro = models.CharField(max_length=255, blank=True, null=True)
    cidade = models.CharField(max_length=255, blank=True, null=True)
    estado = models.CharField(max_length=255, blank=True, null=True)
    telefone = models.CharField(max_length=255, blank=True, null=True)
    cpf = models.CharField(max_length=255, blank=True, null=True)
    cnpj = models.CharField(max_length=255, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    instagram = models.URLField(blank=True, null=True)
    tipo = models.CharField(max_length=255, choices=TIPO_CLIENTE, blank=True, null=True,
                            default='Novo')

    def __str__(self):
        return "%s" % self.nome


class Vendedor(TimeStamped):
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return "%s" % self.user.first_name


class FormaPagamento(TimeStamped):
    tipo = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return "%s" % self.tipo


class StatusPedido(TimeStamped):
    nome_status = models.CharField(max_length=255, blank=True, null=True)
    cor = models.CharField(max_length=255, blank=True, null=True, choices=(
        ('default', 'Padrao'),
        ('info', 'Azul Claro'),
        ('primary', 'Azul Escuro'),
        ('success', 'Verde'),
        ('danger', 'Vermelho'),
        ('warning', 'Amarelo'),
    ))

    def __str__(self):
        return "%s" % self.nome_status


class Pedido(TimeStamped):
    vendedor = models.ForeignKey(Vendedor, blank=True, null=True, on_delete=models.CASCADE)
    cliente = models.ForeignKey(Cliente, blank=True, null=True, on_delete=models.CASCADE)
    forma_pagamento = models.ForeignKey(FormaPagamento, blank=True, null=True, on_delete=models.CASCADE)
    status = models.ForeignKey(StatusPedido, blank=True, null=True, on_delete=models.CASCADE)
    descricao = models.TextField(blank=True, null=True)
    valor_total = MoneyField(decimal_places=2, max_digits=10,
                             default=Money(0, 'BRL'),
                             validators=[
                                 MinMoneyValidator(0),
                                 MaxMoneyValidator(100000),
                             ])


class Item(TimeStamped):
    descricao = models.CharField(max_length=255, blank=True, null=True)
    preco_custo = MoneyField(decimal_places=2, max_digits=10,
                             default=Money(0, 'USD'),
                             validators=[
                                 MinMoneyValidator(0),
                                 MaxMoneyValidator(100000),
                             ])
    valor_unitario = MoneyField(decimal_places=2, max_digits=10,
                                default=Money(0, 'USD'),
                                validators=[
                                    MinMoneyValidator(0),
                                    MaxMoneyValidator(100000),
                                ])
    foto = models.URLField(blank=True, null=True)

    def __str__(self):
        return "%s" % self.descricao


class ItemPedido(TimeStamped):
    pedido = models.ForeignKey(Pedido, blank=True, null=True, on_delete=models.CASCADE)
    qtd = models.IntegerField(default=1)
    item = models.ForeignKey(Item, blank=True, null=True, on_delete=models.CASCADE)
    valor_total = MoneyField(decimal_places=2, max_digits=10,
                             default=Money(0, 'USD'),
                             validators=[
                                 MinMoneyValidator(0),
                                 MaxMoneyValidator(100000),
                             ])


class Orcamento(TimeStamped):
    vendedor = models.ForeignKey(Vendedor, blank=True, null=True, on_delete=models.CASCADE)
    cliente = models.ForeignKey(Cliente, blank=True, null=True, on_delete=models.CASCADE)
    forma_pagamento = models.ForeignKey(FormaPagamento, blank=True, null=True, on_delete=models.CASCADE)
    valor_total = MoneyField(decimal_places=2, max_digits=10,
                             default=Money(0, 'BRL'),
                             validators=[
                                 MinMoneyValidator(0),
                                 MaxMoneyValidator(100000),
                             ])


class ItemOrcamento(TimeStamped):
    orcamento = models.ForeignKey(Orcamento, blank=True, null=True, on_delete=models.CASCADE)
    qtd = models.IntegerField(default=1)
    item = models.ForeignKey(Item, blank=True, null=True, on_delete=models.CASCADE)
    valor_total = MoneyField(decimal_places=2, max_digits=10,
                             default=Money(0, 'USD'),
                             validators=[
                                 MinMoneyValidator(0),
                                 MaxMoneyValidator(100000),
                             ])

app/templates/itemorcamento/create.html
{% extends 'base.html' %}
{% load static %}
{% load form_utils %}
{% block content %}
    <h3 class="page-header">Add ItemOrcamento</h3>

    <div class="row">
        <div class="col-sm-12">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="col-xs-12"> 
 <div class="form-group"> 
 <label>Orcamento:</label> 
{{ form.orcamento }} 
 </div> 
 </div> 
<div class="col-xs-12"> 
 <div class="form-group"> 
 <label>Qtd:</label> 
{{ form.qtd }} 
 </div> 
 </div> 
<div class="col-xs-12"> 
 <div class="form-group"> 
 <label>Item:</label> 
{{ form.item }} 
 </div> 
 </div> 
<div class="col-xs-12"> 
 <div class="form-group"> 
 <label>Valor_total:</label> 
{{ form.valor_total }} 
 </div> 
 </div> 

                    </div>
                    <div class="panel-footer">
                        <div id="actions" class="row">
                            <div class="col-md-12">
                                <button id="btn_salvar" class="btn btn-primary" type="submit">
                                    Add ItemOrcamento
                                </button>
                                <a href="{% url 'ITEMORCAMENTO_list' %}" class="btn btn-default">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#itemorcamento_link').addClass('active');

            $('#id_orcamento').select2({
    ajax: {
        url: '/api/orcamento/',
        dataType: 'json',
        data: function (params) {
            var query = {
                id: params.term
            }
            return query;
        },
        processResults: function (data) {
            new_data = []
            data.forEach(function(elem){
                new_data.push({
                    id: elem.id,
                    text: elem.id
                });
            });
            return {
                results: new_data
            };
        }
    }
});
$('#id_item').select2({
    ajax: {
        url: '/api/item/',
        dataType: 'json',
        data: function (params) {
            var query = {
                descricao: params.term
            }
            return query;
        },
        processResults: function (data) {
            new_data = []
            data.forEach(function(elem){
                new_data.push({
                    id: elem.id,
                    text: elem.descricao
                });
            });
            return {
                results: new_data
            };
        }
    }
});


        });
    </script>
{% endblock %}

app/templates/itemorcamento/delete.html
{% extends 'base.html' %}
{% load static %}
{% load form_utils %}
{% block content %}
    <h3 class="page-header">Delete ItemOrcamento</h3>

    <form action="" method="post">{% csrf_token %}
        <div class="row">
            <div class="text-center">
                <h3>Do you want delete "{{ object }}" ?</h3>
            </div>
        </div>
        <hr/>
        <div id="actions" class="row">
            <div class="col-sm-6">
                <button type="submit" class="btn btn-danger btn-lg btn-block">Yes, delete</button>
            </div>
            <div class="col-sm-6">
                <a href="{% url 'ITEMORCAMENTO_list' %}" class="btn btn-default btn-lg btn-block">Back</a>
            </div>
        </div>
    </form>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#itemorcamento_link').addClass('active');
        });
    </script>
{% endblock %}

app/templates/itemorcamento/detail.html
{% extends 'base.html' %}
{% load static %}
{% load form_utils %}
{% block content %}
    <h3 class="page-header">View ItemOrcamento</h3>

    <div class="row">
        <div class="col-xs-4"> 
 <div class="form-group"> 
 <label>Orcamento:</label> 

{{ object.orcamento }} 
 </div> 
 </div> 
<div class="col-xs-4"> 
 <div class="form-group"> 
 <label>Qtd:</label> 

{{ object.qtd }} 
 </div> 
 </div> 
<div class="col-xs-4"> 
 <div class="form-group"> 
 <label>Item:</label> 

{{ object.item }} 
 </div> 
 </div> 
<div class="col-xs-4"> 
 <div class="form-group"> 
 <label>Valor_total:</label> 

{{ object.valor_total }} 
 </div> 
 </div> 

    </div>
    <hr/>
    <div id="actions" class="row">
        <div class="col-md-12">
            <a class="btn btn-primary" href="{% url 'ITEMORCAMENTO_update' itemorcamento.pk %}">
                Edit
            </a>
            <a href="{% url 'ITEMORCAMENTO_list' %}" class="btn btn-default">Back</a>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#itemorcamento_link').addClass('active');
        });
    </script>
{% endblock %}

app/templates/itemorcamento/list.html
{% extends 'base.html' %}
{% load static %}
{% load form_utils %}
{% block content %}
    <div id="top" class="row">
        <div class="col-sm-3">
            <h2> {{ model_name_plural }}</h2>
        </div>
        <div class="col-sm-3 col-sm-offset-6">
            <a href="{% url 'ITEMORCAMENTO_create' %}" class="btn btn-primary pull-right h2"><i
                    class="fa fa-plus"></i> Add ItemOrcamento
            </a>
        </div>
    </div> <!-- /#top -->
    <hr/>
    <form id="advancedForm" method="get" action="{% url 'ITEMORCAMENTO_list' %}">
        {% csrf_token %}
        <div class="row">
            <div class="col-sm-12">

                {{ filter.form.as_p }}
                 <button type="button" class="btn btn-default" id="clear"><i class="fa fa-close"></i> Clear</button>


            </div>
        </div>
        <hr/>
        <div id="list" class="row">
            <div class="col-md-12">
                <table id="table" class="table table-striped" cellspacing="0" cellpadding="0">
                    <thead>
                    <tr>
                         <th>ID</th> 
 <th>ORCAMENTO</th> 
 <th>QTD</th> 
 <th>ITEM</th> 
 <th>VALOR_TOTAL</th> 

                        <th class="actions">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>

        </div> <!-- /#list -->
    </form>
    <script type="text/javascript">

    $(document).ready(function () {

            function getData() {
                var formData = $('#advancedForm').serializeArray().reduce(function (obj, item) {
                    obj[item.name] = item.value;
                    return obj;
                }, {});
                return formData;
            }

            $('#itemorcamento_link').addClass('active');
            var table = $('#table').DataTable({
            "processing": true,
                "serverSide": true,
                "ajax": "{% url 'ITEMORCAMENTO_list_json' %}",
                "ajax": {
                    "url": "{% url 'ITEMORCAMENTO_list_json' %}",
                    "data": function (d) {
                        return $.extend({}, d, getData());
                    }
                },
                columnDefs: [
                    {
                        targets: -1,
                        data: 'id',
                        "render": function (data, type, row, meta) {
                            return '<a href="/itemorcamento/' + row[0] + '/"><i\n' +
                                '                                    class="fa fa-eye"></i></a>&nbsp;&nbsp;' +
                                '<a href="/itemorcamento/'+row[0]+'/delete/"> <i\n' +
                                '                                    class="fa fa-close"></i></a>';
                        }
                    }
                ],
                order: [[0, "desc"]],
                "language": {
                    "lengthMenu": "Exibir _MENU_ registros por página",
                    "zeroRecords": "Nenhum item encontrado",
                    "info": "Mostrando página _PAGE_ de _PAGES_",
                    "infoEmpty": "Nenhum registro disponível",
                    "emptyTable": "Sem dados disponíveis na tabela",
                    "infoFiltered": "(filtrado do total de _MAX_ registros)",
                    "thousands": ".",
                    "loadingRecords": "Carregando...",
                    "processing": "Processando...",
                    "search": "Buscar:",
                    "paginate": {
                        "first": "Primeiro",
                        "last": "Último",
                        "next": "Próximo",
                        "previous": "Anterior"
                    },
                    "aria": {
                        "sortAscending": ": ativar para classificar a coluna ascendente",
                        "sortDescending": ": ativar para classificar a coluna descendente"
                    }
                }
            });

            $('input').on('keyup', function () {
                table.search('').draw();
            });

            $('#clear').click(function (){
                $("form")[0].reset();
                table.search('').draw();
            });

        });
    </script>

{% endblock %}

app/templates/itemorcamento/update.html
{% extends 'base.html' %}
{% load static %}
{% load form_utils %}
{% block content %}
    <h3 class="page-header">Update ItemOrcamento</h3>

    <div class="row">
        <div class="col-sm-12">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="col-xs-12"> 
 <div class="form-group"> 
 <label>Orcamento:</label> 
{{ form.orcamento }} 
 </div> 
 </div> 
<div class="col-xs-12"> 
 <div class="form-group"> 
 <label>Qtd:</label> 
{{ form.qtd }} 
 </div> 
 </div> 
<div class="col-xs-12"> 
 <div class="form-group"> 
 <label>Item:</label> 
{{ form.item }} 
 </div> 
 </div> 
<div class="col-xs-12"> 
 <div class="form-group"> 
 <label>Valor_total:</label> 
{{ form.valor_total }} 
 </div> 
 </div> 

                    </div>
                    <div class="panel-footer">
                        <div id="actions" class="row">
                            <div class="col-md-12">
                               <button id="btn_atualizar" class="btn btn-primary" type="submit">
                                    Update
                                </button>
                                <a href="{% url 'ITEMORCAMENTO_list' %}" class="btn btn-default">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#itemorcamento_link').addClass('active');

            $('#id_orcamento').select2({
    ajax: {
        url: '/api/orcamento/',
        dataType: 'json',
        data: function (params) {
            var query = {
                id: params.term
            }
            return query;
        },
        processResults: function (data) {
            new_data = []
            data.forEach(function(elem){
                new_data.push({
                    id: elem.id,
                    text: elem.id
                });
            });
            return {
                results: new_data
            };
        }
    }
});
$('#id_item').select2({
    ajax: {
        url: '/api/item/',
        dataType: 'json',
        data: function (params) {
            var query = {
                descricao: params.term
            }
            return query;
        },
        processResults: function (data) {
            new_data = []
            data.forEach(function(elem){
                new_data.push({
                    id: elem.id,
                    text: elem.descricao
                });
            });
            return {
                results: new_data
            };
        }
    }
});

        });
    </script>
{% endblock %}